---
galaxy_info:
  author: "Lucie Leistnerova"
  description: "oVirt change engine/dwh local to remote database"
  company: "Red Hat"
  license: "GPLv3"
  min_ansible_version: 2.0
  platforms:
  - name: EL
    versions:
    - all
  galaxy_tags:
    - migration
