---
galaxy_info:
  author: "Petr Kubica"
  description: "oVirt backup role"
  company: "Red Hat"
  license: "GPLv3"
  min_ansible_version: 1.9
  platforms:
  - name: EL
    versions:
    - all
  galaxy_tags:
    - installer
