---
galaxy_info:
  author: "Petr Kubica"
  description: "oVirt DB installer"
  company: "Red Hat"
  license: "GPLv3"
  min_ansible_version: 2.0
  platforms:
  - name: EL
    versions:
    - all
  galaxy_tags:
    - installer
