---
- name: set engine variables
  set_fact:
    engine_ip: "{% if hostvars[groups['engine'][0]]['ansible_default_ipv4']['address'] is defined %}{{ hostvars[groups['engine'][0]]['ansible_default_ipv4']['address'] }}{% else %}{{ groups['engine'][0] }}{% endif %}"
# first dump databases on engine and get connection variables
- name: dump databases
  include_role:
    name: ovirt-engine-db-dump
  vars:
    ovirt_engine_db_dump_dwh: "{{ ovirt_engine_dwh_to_remote_db }}"
    ovirt_engine_db_dump_start_services: False
    ovirt_engine_db_dump_local_dir: "{{ playbook_dir }}/engine_dump"
  when: ovirt_type == "engine"
- name: get engine variables from file
  include_vars:
    file: "{{ playbook_dir }}/engine_dump/engine_variables.json"
    name: ovirt_engine_db_dump_engine_db
  when: ovirt_engine_to_remote_db == True
- name: get DWH variables from file
  include_vars:
    file: "{{ playbook_dir }}/engine_dump/dwh_variables.json"
    name: ovirt_engine_db_dump_dwh_db
  when: ovirt_engine_dwh_to_remote_db == True
# create databases on remote server and import data
- name: create databases and import data
  include_role:
    name: ovirt-engine-remote-db
  vars:
    ovirt_engine_remote_db_port: "{{ ovirt_engine_db_dump_engine_db['ENGINE_DB_PORT']|regex_replace('\"', '') }}"
    ovirt_engine_db_name: "{{ ovirt_engine_db_dump_engine_db['ENGINE_DB_DATABASE']|regex_replace('\"', '') }}"
    ovirt_engine_db_user: "{{ ovirt_engine_db_dump_engine_db['ENGINE_DB_USER']|regex_replace('\"', '') }}"
    ovirt_engine_db_password: "{{ ovirt_engine_db_dump_engine_db['ENGINE_DB_PASSWORD']|regex_replace('\"', '') }}"
    ovirt_engine_remote_db: "{{ ovirt_engine_to_remote_db }}"
    ovirt_engine_dwh_remote_db: "{{ ovirt_engine_dwh_to_remote_db }}"
    ovirt_engine_dwh_db_name: "{{ ovirt_engine_db_dump_dwh_db['DWH_DB_DATABASE']|regex_replace('\"', '') }}"
    ovirt_engine_dwh_db_user: "{{ ovirt_engine_db_dump_dwh_db['DWH_DB_USER']|regex_replace('\"', '') }}"
    ovirt_engine_dwh_db_password: "{{ ovirt_engine_db_dump_dwh_db['DWH_DB_PASSWORD']|regex_replace('\"', '') }}"
    ovirt_engine_remote_db_force: True
    ovirt_engine_remote_db_dump: "{{ ovirt_engine_db_dump_local_dir }}/engine.sql"
    ovirt_engine_remote_db_dwh_dump: "{{ ovirt_engine_db_dump_local_dir }}/dwh.sql"
    ovirt_engine_remote_db_access:
      -
        type: host
        address: "{{ engine_ip }}/32"
        method: md5
  when: ovirt_type == "remote_db"
# set engine from local to remote db
- include: set-engine.yml
  when: ovirt_type == "engine"
# clean
- name: remove dump files from local
  local_action:
    file path={{ playbook_dir }}/engine_dump state=absent
