---
- name: Include correct variables based on system
  include_vars: "{{ ovirt_collect_logs_from_system }}.yml"

- name: Ensure required archive tools
  yum:
    name: ['gzip', 'tar']
    state: "present"
  register: yum_result
  until: yum_result is success
  retries: 3
  delay: 10

# Prepare place to store data

- name: Clean temporary directory and previous archive
  file:
    path: "{{ item }}"
    state: "absent"
  with_items:
    - "{{ ovirt_collect_logs_tmp_dir }}"
    - "{{ ovirt_collect_logs_archive }}"

- name: Create temporary directory
  file:
    path: "{{ ovirt_collect_logs_tmp_dir }}"
    state: "directory"
    mode: "0777"

# Collect common stuff
- name: Dump system information using shell commands
  shell: "{{ item.value }} &> {{ ovirt_collect_logs_tmp_dir }}/{{ item.key }}.txt"
  with_dict: "{{ ovirt_collect_logs_shell_commands }}"
  ignore_errors: true
  tags:
    - skip_ansible_lint # check for shell module is not working correctly in Lint

- name: Check if log /var/log/messages exists
  stat: path=/var/log/messages
  register: message_file_exits

- name: Collect log /var/log/messages
  file:
    src: "{{ item.src }}"
    dest: "{{ ovirt_collect_logs_tmp_dir }}/{{ item.dest }}"
    state: link
  with_items:
    - { src: "/var/log/messages", dest: "messages" }
  when: message_file_exits

# Collect system specific stuff

- name: Collect logs from specific system
  include_tasks: "{{ ovirt_collect_logs_from_system }}.yml"

# Fetch stuff to local system
- name: Archive logs
  shell: "tar {{ ovirt_collect_logs_tar_optional_params }}
            -hczf {{ ovirt_collect_logs_archive }}
            {{ ovirt_collect_logs_tmp_dir }}"
  ignore_errors: true
  tags:
    - skip_ansible_lint # achive module has insufficient functionality

- name: Fetch logs
  fetch:
    src: "{{ ovirt_collect_logs_archive }}"
    dest: "logs/{{ ovirt_collect_logs_from_system }}-{{ ansible_hostname }}/ovirt-engine-logs.tar.gz"
    flat: yes

- name: Remove /var/log/messages if it was not there before
  file:
    path: /var/log/messages
    state: absent
  when: not message_file.stat.exists
