---
galaxy_info:
  author: "Meni Yakove"
  description: "Set parameters for ovirt-iso-uploader in isouploader.conf"
  company: "Red Hat"
  license: "GPLv3"
  min_ansible_version: 1.9
  platforms:
    - name: EL
      versions:
        - all
  galaxy_tags:
    - installer
