---
# delete the temp file which was created for grep comparison
- name: delete engine-rename engine rename logs
  file:
    path: '/tmp/engine-rename-logs-current.grep'
    state: 'absent'

- name: delete engine-rename expected log files
  file:
    path: '/tmp/check-engine-name-expected-result.grep'
    state: 'absent'
