- name: Install latest {{ ovirt_guest_agent_pkg_prefix }}-guest-agent
  yum:
    name: "{{ item }}"
    state: latest
  with_items:
    - "{{ ovirt_guest_agent_pkg_prefix }}-guest-agent"
  register: yum_result
  until: yum_result is success
  retries: 3
  delay: 10
  notify: enable and start guest-agent service
  tags:
    - skip_ansible_lint
