---
- name: Register the engine name stored inside the files in directory `/etc/ovirt-engine`
  shell: grep -R {{ ovirt_engine_rename_new_fqdn }} /etc/ovirt-engine
  register: grep_output_remote_run
  ignore_errors: yes

# ^ ignore_errors? 
# grep returns an exit code of 1 when it doesn't match any lines. Ansible then
# interprets this (actually any status code other than 0 from a shell/command
# task) as an error and so promptly fails.

- name: Saving the above diff result
  local_action: copy content={{ grep_output_remote_run.stdout }} dest=/tmp/engine-rename-expected.grep
  notify:
    - delete expected grep file

- debug: msg="The command grep -R {{ ovirt_engine_rename_new_fqdn }} /etc/ovirt-engine returned {{ grep_output_remote_run.stdout }}"

- name: Copy the expected result to /tmp on the remote vm to be compared
  template:
    src: check-engine-name-expected-result.grep.j2
    dest: /tmp/check-engine-name-expected-result.grep
  notify:
    - delete temp expected result file

# if the engine-name is already at the state where we want it to be
- name: Comparing the grep diff for the one that we expect and the one we just ran
  shell: diff /tmp/check-engine-name-expected-result.grep /tmp/engine-rename-expected.grep
  register: grep_diff
  ignore_errors: yes

- name: Running engine-rename command (if the engine-name diff command status is not 0)
  shell: |
    /usr/share/ovirt-engine/setup/bin/ovirt-engine-rename \
    --newname={{ ovirt_engine_rename_new_fqdn }} \
    --otopi-environment="OSETUP_RENAME/forceIgnoreAIAInCA=bool:'True' \
    OVESETUP_CORE/engineStop=bool:'True' \
    OSETUP_RENAME/confirmForceOverwrite=bool:'False'"
  when: grep_diff.rc != 0
  register: engine_rename_result

- name: Changing the system host name to reflect the new engine-name
  shell: hostnamectl set-hostname {{ ovirt_engine_rename_new_fqdn }}

- debug: msg="change your /etc/hosts file to reflect to the new changed ovirt-engine name"

- name: Checking if the engine-rename is successfull
  shell: grep -R {{ ovirt_engine_rename_new_fqdn }} /etc/ovirt-engine
  register: final_check

- name: Engine rename successfull or not?
  shell: echo Engine Rename successfull
  when: final_check.rc == 0

- name: check health status of page
  uri:
    url: "http://{{ ovirt_engine_rename_new_fqdn }}/ovirt-engine/services/health"
    status_code: 200
  register: health_page
  retries: 12
  delay: 10
  until: health_page|success
