---
ovirt_collect_logs_tmp_dir: "/var/tmp/ovirt-logs-{{ ovirt_collect_logs_from_system }}"
ovirt_collect_logs_archive: "/var/tmp/ovirt-logs-{{ ovirt_collect_logs_from_system }}.tar.gz"
ovirt_collect_logs_shell_commands:
  rpm-list: "rpm -qa | sort -f"
  yum-list: "yum list installed"
  services: "systemctl -t service --failed --no-legend | awk '{print $1}'
            | xargs -r -n1 journalctl -u"
  iptables: "iptables -L"
  lsof: "lsof -P"
  pstree: "pstree -p"
  sysctl: "sysctl -a"
  netstat: "netstat -lnp"
  lsmod: "lsmod"
  lspci: "lspci"
  memory_usage: "ps -e -orss=,args= | sort  -b -k1,1n | tac"
