---
# ovirt-common tasks
- name: upgrading all packages
  yum:
    name: '*'
    state: "latest"
  tags:
    - skip_ansible_lint

# install libselinux-python on machine - selinux policy
- name: install libselinux-python for ansible
  yum:
    name: libselinux-python
    state: "present"

# backup repos
- name: creating directory repo-backup in yum.repos.d
  file:
    path: /tmp/repo-backup
    state: directory

- name: create repository backup
  shell: 'cp /etc/yum.repos.d/*.repo /tmp/repo-backup'
  tags:
    - skip_ansible_lint

# get repository templates
- name: deploy repository file
  yum_repository:
    name: "ovirt-main"
    file: "ovirt"
    description: "oVirt main repo"
    baseurl: "{{ ovirt_repo }}"
    gpgcheck: no
  when: ovirt_repo is defined

- name: copy dependency repository file
  yum_repository:
    name: "ovirt-dependency"
    file: "ovirt"
    description: "oVirt dependency repo"
    baseurl: "{{ ovirt_dependency_repo }}"
    gpgcheck: no
  when: ovirt_dependency_repo is defined

- name: install rpm repository package
  yum:
    name: "{{ ovirt_rpm_repo }}"
    state: present
  when: ovirt_rpm_repo is defined
